services:
  mongo:
    image: mongo:6
    container_name: monitoring-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017/admin", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: monitoring-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: monitoring-redis-ui
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: monitoring-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - ./apps/api/.env.production
    environment:
      NODE_ENV:    production
      PORT:        4000
      MONGODB_URI: mongodb://mongo:27017/monitoring_platform
      REDIS_URL:   redis://redis:6379
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.worker
    container_name: monitoring-worker
    restart: unless-stopped
    env_file:
      - ./apps/api/.env.production
    environment:
      NODE_ENV:    production
      MONGODB_URI: mongodb://mongo:27017/monitoring_platform
      REDIS_URL:   redis://redis:6379
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mongo_data:
  redis_data: