services:
  mongo:
    image: mongo:6
    container_name: monitoring-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017/admin", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Redis as the Message Broker
  # alpine = lightweight image 
  # appendonly yes 
  redis:
    image: redis:7-alpine
    container_name: monitoring-redis
    restart: unless-stopped
    ports:
      - "6380:6379"    
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Visual UI for Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: monitoring-redis-ui
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: monitoring-api
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGODB_URI: mongodb://mongo:27017/monitoring_platform
      JWT_SECRET: change_me_in_compose
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: "*"
      REDIS_URL: redis://redis:6379   # Redis address inside the Docker network
    depends_on:
      mongo:
        condition: service_healthy
      redis:                          # Waiting for Redis to be healthy first
        condition: service_healthy

volumes:
  mongo_data:
  redis_data:   